name: Auto Release on latest commit

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Get commit info
        id: commit
        run: |
          echo "sha=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT
          echo "message<<EOF" >> $GITHUB_OUTPUT
          git log -1 --pretty=%B >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run build script
        run: ./build.sh

      - name: Delete previous release and tag
        run: |
          gh release delete latest --yes || true
          git tag -d latest || true
          git push origin :refs/tags/latest || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new tag
        run: |
          git tag latest
          git push origin latest

      - name: Create new release
        run: |
          gh release create latest \
          --title "${{ steps.commit.outputs.sha }}" \
          --notes "Release for commit ${{ steps.commit.outputs.sha }}: ${{ steps.commit.outputs.message }}" \
          --target ${{ github.sha }} \
          build/dist/nuxlper.tar
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
