name: Auto Release Latest

on:
  push:
    branches:
      - autopublish  # Change to your default branch if different

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh -y

      - name: Get current commit SHA
        id: sha
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Run build script
        run: ./build.sh

      - name: Delete previous release and tag
        run: |
          gh release delete latest --yes || true
          git tag -d latest || true
          git push origin :refs/tags/latest || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new tag
        run: |
          git tag latest
          git push origin latest

      - name: Create new release
        run: |
          gh release create latest --title "${{ steps.sha.outputs.sha }}" --notes "Release for commit ${{ steps.sha.outputs.sha }}" ./path/to/artifact
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
